MutualCrossAttn_p2p: true
MutualCrossAttn: false
MutualCrossAttn_layers:
- 6
- 7
MutualCrossAttn_steps:
- 0
- 40
MutualSelfAttn: false
MutualSelfAttn_layers:
- 7
- 16
MutualSelfAttn_steps:
- 0
- 50
app_guidance:
  block_type: spatial
  blocks:
  - up_blocks.1
  - up_blocks.2
  cross_attn_blocks:
  - up_blocks.1
  - up_blocks.2
  cross_attn_mask_tr_app: 0.3
  cross_attn_mask_tr_example: 0.2
  weight_each:
  - 20000
  - 10000
cfg_scale: 7.5
dreambooth_path: models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors
early_stop_epsilon: 1.0e-05
function_type: edit
grad_guidance_scale: 1.0
grad_guidance_threshold: null
inversion_prompt: a cat sitting next to a mirror
model_config: configs/model_config/model_config.yaml
motion_module: models/Motion_Module/v3_sd15_mm.ckpt
negative_prompt: ""
new_prompt: watercolor painting of a cat sitting next to a mirror
null_inner_steps: 1
num_inference_step: 50
number: 92425
prompt_type: long
score_guide:
- 0.5
- 0.0
- 0.0
- 0.5
score_steps: 1
temp_guidance:
  blocks:
  - up_blocks.1
  - up_blocks.2
  weight_each:
  - 20000
  - 10000
video_path: resources/walk.mp4
p2p_cross_is_replace_controller: false
p2p_cross_replace_steps: 0.8
p2p_cross_replace_layers:
  - 6
  - 7
p2p_self_replace_steps: 0.7
p2p_blend_word_base: 
p2p_blend_word_new: 
p2p_eq_params_words: 
  - watercolor
p2p_eq_params_values: 
  - 5


