MutualCrossAttn: false
MutualCrossAttn_layers:
- 0
- 16
MutualCrossAttn_steps:
- 0
- 40
MutualSelfAttn: true
MutualSelfAttn_layers:
- 7
- 16
MutualSelfAttn_steps:
- 0
- 50
app_guidance:
  block_type: spatial
  blocks:
  - up_blocks.1
  - up_blocks.2
  cross_attn_blocks:
  - up_blocks.1
  - up_blocks.2
  cross_attn_mask_tr_app: 0.3
  cross_attn_mask_tr_example: 0.2
  weight_each:
  - 20000
  - 10000
cfg_scale: 7.5
dreambooth_path: models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors
early_stop_epsilon: 1.0e-05
function_type: edit
grad_guidance_scale: 1.0
grad_guidance_threshold: null
inversion_prompt: Astronaut walks on the shore of a body of water with growing alien
  plants that glow, under an ethereal sky.
model_config: configs/model_config/model_config.yaml
motion_module: models/Motion_Module/v3_sd15_mm.ckpt
negative_prompt: ugly, deformed, noisy, blurry, distorted, out of focus, bad anatomy,
  extra limbs, poorly drawn face, poorly drawn hands, missing fingers
new_prompt: Thanos walks on the shore of a body of water with growing alien plants
  that glow, under an ethereal sky.
null_inner_steps: 10
num_inference_step: 50
number: 83
prompt_type: long
score_guide:
- 0.5
- 0.25
- 0.0
- 0.1
score_steps: 50
temp_guidance:
  blocks:
  - up_blocks.1
  - up_blocks.2
  weight_each:
  - 20000
  - 10000
video_path: resources/walk.mp4
